apiVersion: v1
appVersion: '>=1.12.0'
description: A Helm Chart for Edge 2
icon: https://start.backbase.com/favicon.png
keywords:
- ips
- edge
maintainers:
- email: developer-enablement-backend-foundation@backbase.com
  name: Backend Foundation Team
name: edge
version: 0.12.5
