apiVersion: v1
appVersion: 1.8.0
description: A Helm Chart for Backbase Identity - OIDC Token Converter
icon: https://start.backbase.com/favicon.png
keywords:
- identity
- token-converter
- oidc-token-conveter
maintainers:
- email: identity-core@backbase.com
  name: Identity Core Squad
name: oidc-token-converter
version: 0.3.0-rc.42
