{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "backbase-app.fullname" . }}-data
  labels:
{{ include "backbase-app.labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- $storageClass := include "backbase-app.persistence.storage-class" . -}}
{{- if $storageClass }}
{{- if (eq "-" $storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ $storageClass | quote }}
{{- end }}
{{- end -}}
{{- end }}
