apiVersion: v1
appVersion: '>=1.12.0'
description: A Helm Charts for Registry
icon: https://start.backbase.com/favicon.png
keywords:
- ips
- registry
maintainers:
- email: developer-enablement-backend-foundation@backbase.com
  name: Backend Foundation Team
name: registry
version: 0.8.3
