{{- if .Values.customFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backbase-app.fullname" . }}-customfiles
  labels:
{{ include "backbase-app.labels" . | indent 4 }}
data:
{{- range $key, $val := .Values.customFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
