{{- if and (or .Values.global.podDisruptionBudget .Values.podDisruptionBudget) (or (gt .Values.replicaCount 1.0) (gt .Values.global.replicaCount 1.0)) -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backbase-app.fullname" . }}-pdb
  labels:
    {{- include "backbase-app.match-labels" . | nindent 4 }}
spec:
  {{- include "backbase-app.pdb" . | nindent 2 }}
  selector:
    matchLabels:
      {{- include "backbase-app.match-labels" . | nindent 6 }}
{{- end -}}
