apiVersion: v1
appVersion: "2022.02"
description: A Helm Chart for Backbase Identity Integration
icon: https://start.backbase.com/favicon.png
keywords:
- identity
- identity-integration
maintainers:
- email: identity-lifecycle@backbase.com
  name: Identity Lifecycle Management Squad
name: identity-integration
version: 0.1.8
