{{- if or .Values.global.serviceAccount.create .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "backbase-app.serviceAccountName" . }}
  labels:
{{ include "backbase-app.labels" . | indent 4 }}
{{- end -}}